### ISSUE TITLE
Kerberos Auth non-working since 6.0.0

### ISSUE THREAD

**Issue by infabo** [mguessan/davmail#168]
I have no additional info right now, as i downgraded to 5.5.1 again.

**Comment by mguessan** [comment]
Thanks for your feedback, tried a quick fix available in trunk build.

Please let me know if this helps in your case.

**Comment by infabo** [comment]
I don't want set up the build-env for davmail. I'll await the patch release 6.0.1. Thanks

**Comment by infabo** [comment]
Still not working in 6.0.1

<html>
<body>


Tue Dec 07 09:51:54 CET 2021 (1638867114817) | ImapConnection-48116 | 128 | WARN |   | org.apache.http.impl.auth.HttpAuthenticator | NEGOTIATE authentication error: No valid credentials provided (Mechanism level: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)) | org.apache.http.impl.auth.HttpAuthenticator.generateAuthResponse(HttpAuthenticator.java:207) |  
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

<html>
<body>


Tue Dec 07 09:51:54 CET 2021 (1638867114875) | ImapConnection-48116 | 131 | DEBUG |   | davmail | > 27 NO LOGIN Kerberos authentication failed | davmail.ui.tray.DavGatewayTray.displayMessage(DavGatewayTray.java:100) |  
-- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by infabo** [comment]
@mguessan Any info I can provide to help on this issue?

**Comment by b2ag** [comment]
Is this still a thing? Should I keep on trying to set up davmail to work with kerberos or should I just don't care about caldav and all the strange errors which davmail tends to bring to the table?

**Comment by mguessan** [comment]
Still unable to reproduce the issue, need to build a new environment with Kerberos enabled.

In order to debug the java side the java command line must have an additional argument:

`-Dsun.security.krb5.debug=true`

**Comment by mguessan** [comment]
Ok had a look at this, I think I found the missing part: DavMail kerberos logic not properly taken into account by HttpClient 4

**Comment by mguessan** [comment]
Ok first try at new Kerberos implementation available in svn/git... still untested as my test lab is unavailable.

The new SpNegoScheme should be able to retrieve cached kerberos token or use callbacks to let user provide valid credentials and create a new token.

**Comment by arjan-s** [comment]
Sorry it took a while to test this, but current master works for me!
Do you have a roadmap for when this could get released?

**Comment by mguessan** [comment]
Next release should probably happen soon, just have some library upgrades to do before

**Comment by arjan-s** [comment]
I just upgraded to 6.1.0 and can confirm the problem is fixed. Thanks!

**Comment by b2ag** [comment]
I can't get it to work properly.

Without sending the correct password it jumps straight to "Kerberos authentication failed" and is not even trying anything with the credentials cache file. When sending the correct password I managed to get a working Kerberos auth using the cached credentials. Sadly it's ignoring my krb5.conf regarding ticket cache file location, but seems to handle the KRB5CCNAME environment variable correct.

I'm only interested in CalDAV and didn't test anything else.

I assume it is a bug that I need to send the correct password to get the Kerberos  layer to actually do something. Am I right? I've read the password should be ignored by davmail in Kerberos mode. But for me this quite obviously isn't the case.

**Comment by mguessan** [comment]
The kerberos logic is in davmail.http.KerberosHelper, it will first try to fetch the cached ticket (System.getenv().get("KRB5CCNAME")), if this does not work the credentials callbackhandler will provide username/password provided by client.

So you are right if something is wrong with ticket cache the provided credentials are used.

DavMail does not rely on krb5.conf file, parameters are prepared in KerberosLoginConfiguration.

Please make sure debug level is DEBUG and check davmail.log for more details.

You may also want to launch DavMail with additional -Dsun.security.krb5.debug=true flag

**Comment by b2ag** [comment]
I already used both of the debug settings you proposed. I don't know what was happening, only reporting what I've observed. It only worked when both are present: a valid password and the tgt in Kerberos mode. Make what you want out of it. I ditched Kerberos also because of bad design like not supporting Unix named sockets which effectively reduces davmail hosts to single user systems.

**Comment by mguessan** [comment]
@b2ag I eventually managed to rebuild a full environment with on prem Exchange and a linux box and managed to reproduce the Kerberos authentication issue.

Basically with default settings Java and thus DavMail is unable to access the ticket cache. Root cause is the KEYRING setting in /etc/krb5.conf

```
default_ccache_name = KEYRING:persistent:%{uid}
```
The workaround is to set a value for KRB5CCNAME to switch to file ticket cache mode supported by Krb5LoginModule.

There was also another bug on credentials handling: HttpClient tried to use username/password as NTCredentials instead of using the GSS Kerberos mode.

Issues fixed and introduced a new `-kerberos` command line option to validate configuration

```
# set ticket cache path
KRB5CCNAME=/tmp/krb5cc_$(id -u)

# Reset authentication
kdestroy -A

# Authenticate
kinit 

# Check ticket, should have a FILE ticket cache
klist

# Check authentication, should succeed without prompting for credentials
davmail -kerberos

```

**Comment by mguessan** [comment]
Closing as patch included in latest release.

Also improved documentation.

**Comment by b2ag** [comment]
Can confirm this works for me. 

I tested by starting with a fresh config and setting
```
davmail.url=https://outlook.centos.local/ews/exchange.asmx
davmail.mode=ExchangeEWS
davmail.enableKerberos=true
```
than running `curl 'http://myuser@127.0.0.1:1080/users/myuser/calendar'`. And it worked!
I'm mostly interested in CalDAV as I've already convinced my "Windows admins" to enable IMAP for me. So didn't test anything else.

Thanks for fixing the issue! ❤️
